status_message: 
client_id: 
max_text: 100000
max_images: 5
max_messages: 25
temperature: 1.0
use_plain_responses: false
use_google_search: true
use_url_context: true
thinking_level: "high" # Gemini 3 Config: "minimal", "low", "medium", "high"
thinking_budget: -1 # Gemini 2.5 Config: -1 (Dynamic), 0 (Off), or Token Count (Max: 32768 for Pro, 24576 for Flash)
allow_dms: false

permissions:
  users:
    allowed_ids: []
    blocked_ids: []
    admin_ids: []
  roles:
    allowed_ids: []
    blocked_ids: []
  channels:
    allowed_ids: []
    blocked_ids: []

models:
  - gemini-2.5-flash
  - gemini-2.5-flash-lite

system_prompt: |
  